/**
 * strategyChecklistThresholds.js — My Strategy v1 기준 충족도 임계값
 *
 * 승률·수익 확률 표현에 쓰지 않는다.
 */

export const STRATEGY_CHECKLIST_THRESHOLDS = Object.freeze({
  HTF_MAX: 30,
  HTF_4H_ALIGNED: 15,
  HTF_4H_MIXED: 8,
  HTF_1H_ALIGNED: 10,
  HTF_1H_MIXED: 5,
  HTF_BOTH_ALIGNED_BONUS: 5,

  LOCATION_MAX: 25,
  LOCATION_PRIMARY: 7,
  LOCATION_CONTEXT: 6,
  LOCATION_OBSERVE: 2,

  MARKET_MAX: 25,
  MARKET_15M_ALIGNED: 6,
  MARKET_15M_MIXED: 3,
  MARKET_CVD_ALIGNED: 6,
  MARKET_VOLUME_OK: 5,
  MARKET_OI_ALIGNED: 5,
  MARKET_FUNDING_OK: 3,

  RISK_MAX: 20,
  RISK_HAS_STOP: 8,
  RISK_HAS_TARGET: 6,
  RISK_NO_FOMO: 6,

  READY_MIN: 75,
  NOT_READY_MIN: 50,

  REENTRY_WINDOW_MS: 30 * 60 * 1000,
  REENTRY_MAX: 2,
  CONSECUTIVE_LOSS_MIN: 2,

  VOLUME_RATIO_OK: 1,
  BUY_SHARE_OK: 52,
  SELL_SHARE_OK: 52,
  OI_CHANGE_OK: 0.15,
  FUNDING_EXTREME: 0.001,
})
