import React from 'react'
import { JOURNAL_RECORD_TYPES } from '../../../shared/tradeJournal.js'
import { journalDate, journalOutcomeLabel } from '../../utils/tradeJournalView.js'

export default function TradeJournalList({ trades = [], loading, error, filter, onFilter, onSelect, onCreate, onRefresh, hasMore, onMore, offset = 0, onPrevious }) {
  return <section className="lab-journal-list" aria-label="매매일지 · 복기">
    <header className="lab-section-head"><div><div className="lab-eyebrow">MY JOURNAL</div><h2>내가 남긴 시나리오</h2></div><button type="button" className="lab-button" onClick={onRefresh}>목록 새로고침</button></header>
    <div className="lab-filters" aria-label="일지 필터">{[['all', '전체 기록'], ['review', '복기할 기록'], ['reviewed', '복기 완료']].map(([key, label]) => <button type="button" key={key} aria-pressed={filter === key} className={`lab-filter${filter === key ? ' is-selected' : ''}`} onClick={() => onFilter(key)}>{label}</button>)}</div>
    {error ? <p className="lab-error" role="alert">{error}</p> : loading && !trades.length ? <p className="lab-empty" role="status">일지를 불러오는 중…</p> : !trades.length ? <div className="lab-empty"><span className="lab-empty__icon">✎</span><h3>{filter === 'all' ? '아직 남긴 시나리오가 없습니다.' : filter === 'review' ? '지금 복기할 기록이 없습니다.' : '복기를 마친 기록이 없습니다.'}</h3><p>{filter === 'all' ? '차트에서 본 구간과 근거를 남겨보세요. 이후 움직임을 이 기록에 이어서 쌓습니다.' : '시간별 결과가 도착한 기록을 열고, 다음에 고칠 한 가지를 적어보세요.'}</p>{filter === 'all' && <button className="lab-button lab-button--primary" type="button" onClick={onCreate}>첫 시나리오 남기기</button>}</div> : <ul className="lab-journal-cards">{trades.map((trade) => <li key={trade.id}><button type="button" className="lab-journal-card" onClick={() => onSelect(trade.id)}><div className="lab-journal-card__top"><span className={`lab-direction lab-direction--${trade.direction.toLowerCase()}`}>가상 {trade.direction}</span><span>{JOURNAL_RECORD_TYPES[trade.recordType] || '관찰'} 기록</span><time>{journalDate(trade.createdAt)}</time></div><h3>{trade.journal?.journalTitle || trade.journal?.scenarioText || trade.userNote || trade.entryReason || '진입 시나리오를 남겨주세요'}</h3><div className="lab-journal-card__tags">{(trade.journal?.reasonTags || []).slice(0, 5).map((tag) => <span key={tag}>{tag}</span>)}</div><div className="lab-journal-card__bottom"><span>{trade.symbol} · 4h 후 <b>{journalOutcomeLabel(trade, '4h')}</b></span><span>{trade.journal?.imageCount ? `캡처 ${trade.journal.imageCount}장 · ` : ''}{trade.journal?.reviewedAt ? '복기 완료' : '일지 열기'} ↗</span></div></button></li>)}</ul>}
    <div className="lab-pagination">{offset > 0 && <button className="lab-button" type="button" onClick={onPrevious} disabled={loading}>이전 기록</button>}{hasMore && <button className="lab-button" type="button" onClick={onMore} disabled={loading}>다음 기록</button>}</div>
    <p className="lab-muted lab-journal-footnote">기록 기반 참고를 위한 공간입니다. 유사 기록 통계는 표본과 조건을 검증한 뒤 추가합니다.</p>
  </section>
}
